<div align="right" class="messagebox">

<form method="post" action="">

        Load a different template >

        <select name="newFormConfig">
            
<?php 
// If a template was selected, select it after reload.
if ( true == isset ( $this->loadedFormConfig ) ) {
    echo '<option value="'. $this->loadedFormConfig .'">'. $this->loadedFormConfig .'</option>';
}
?>
            
            <option value="">- please select -</option>

<?php
// Read all XML files in formconfig folder and generate a list.
foreach ( Tools::getConfigFileList () as $file )
{
    echo '<option value="'. $file .'" label="'. $file .'">'. $file .'</option>';
}
?>
        </select>
        <input type="submit" value=">>"/>
    
    </div>

</form>


<!-- Content of "headline" tag -->
<form method="post" action="<?php echo $this->actionUrl; ?>">


<!-- Content of "headline" tag -->
<h1><?php echo $this->form->headline; ?></h1>
        
        
<!-- Content of "introduceText" tag -->
<?php echo $this->form->introduceText; ?>
                
                
<!-- Iterate about sections -->
<?php 
foreach ( $this->form->sections as $section )
{
    echo '<br><br>';
    echo '<h3>'. $section ['caption'] .'</h3>';
    
    ## Iterate about predicates, only if predicate was set ##
    if ( true == isset ( $section ['predicate'] ) )
        foreach ( $section ['predicate'] as $predicate )
        {
            echo '<br>'. $predicate ['caption'];
            
            echo '('. $predicate ['type'] .') ';
            
            echo '1' == $predicate ['mandatory']
                 ? '* &nbsp;'
                 : '';

            // Output HTML code which belongs to this type    
            echo FormgeneratorController::getHtmlForType (  $predicate ['type'],
                                                            $predicate ['typeparameter'], 
                                                            $predicate ['predicateuri'],
                                                            $this->form->targetclass );
        }
                    
    
    ## Iterate about nestedconfigs, only if nestedconfig was set ##
    if ( true == isset ( $section ['nestedconfig'] ) )
    {
        
        // Include formulas from nested configs
        foreach ( $section ['nestedconfig'] as $nestedconfig )
        {
            foreach ( $nestedconfig ['form']->sections as $section )
            {                        
                // Iterate about predicates, only if predicate was set
                if ( true == isset ( $section ['predicate'] ) )
                    foreach ( $section ['predicate'] as $predicate )
                    {
                        echo '<br>'. $predicate ['caption'];
            
                        echo '('. $predicate ['type'] .') ';
                        
                        echo '1' == $predicate ['mandatory']
                             ? '* &nbsp;'
                             : '';

                        // Output HTML code which belongs to this type    
                        echo FormgeneratorController::getHtmlForType ( $predicate ['type'], 
                                                                       $predicate ['typeparameter'],  
                                                                       $predicate ['predicateuri'],
                                                                       $nestedconfig ['form']->targetclass );
                    }
            }
        }
    }
}
?>
    <input type="hidden" name="loadedFormConfig" value="<?php echo $this->loadedFormConfig; ?>"/>

    <p><input type="submit" value="Send"/></p>
</form>
