<?php
/**
 * Template for form action
 *
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<?php if ("box" == $this->layout) { ?>
<!-- important variables -->
<script type="text/javascript">
    tempboxdata = {};
    $.data(tempboxdata, "form", <?php echo json_encode ($this->form->getDataAsArrays ()); ?>);
</script>
<?php } ?>

<!-- only if the form is no in box layout -->
<?php if ("box" != $this->layout) { ?>

    <!-- formular select box, show only if form is no box and no report-->
    <?php if ("report" != $this->form->getFormulaType()) { ?>
        <!-- important variables -->
        <script type="text/javascript">
            var url = '<?php echo $this->url; ?>';
            var urlBase = '<?php echo $this->urlBase ?>';
            var urlMvc = urlBase + 'formgenerator/';
    
            var data = {};
            $.data(data, "form", <?php echo json_encode ($this->form->getDataAsArrays ()); ?>);
         </script>
    
        <!-- set the title of the action -->
        <?php $this->placeholder('main.window.title')->set($this->form->getTitle()); ?>
    
        <!-- div for boxform -->
        <div id="boxes"></div>

    
        <div align="right" class="messagebox">
            <form id="formformlist" method="get" action="">
    
                <?php echo $this->_translate->_('Available forms:'); ?>
    
                <select id="selectformlist" name="file">
                    <?php
                        // Read all XML files in formconfig folder and generate a list.
                        foreach ( $this->formList as $file )
                        {
                            echo '<option value="'. $file .'" label="'. $file .'"' . ($this->form->getXmlFile() == $file ? ' selected="selected"' : "") . '>' .
                            substr_replace($file, strtoupper(substr($file, 0, 1)), 0, 1) .'</option>' . "\n";
                        }
                    ?>
                </select>
            </form>
        </div>

        <script type="text/javascript">
            $('#selectformlist').change(function() {
                $('#formformlist').submit();
            });
        </script>
    <?php } ?>

<?php } else { echo $this->boxtoolbar; ?>
    <div class="clear"></div>
    <div id="boxdialog">
        <div>
<?php } ?>

<!-- formula -->
<form id="mainform" method="post" action="">

    <div class="content">
        <h2><?php echo $this->form->getTitle(); ?></h2>
    </div>

    <?php if('' != $this->form->getDescription()) { ?>

    <div class="content">
        <?php echo $this->form->getDescription(); ?>
    </div>

    <?php } ?>

    <!-- select a resource of a specific type -->
    <?php if (true == isset($this->resourcesOfType)) { ?>

        <form method="post" action="<?php echo $this->url; ?>form/">
            <div class="content">
                <div class="predicateTitle"><?php echo $this->_translate->_('Please select:'); ?></div>

                <div class="predicateValue">
                    <select name="r">

                        <option value=""><?php echo $this->_translate->_('please select'); ?></option>

                    <?php foreach ($this->resourcesOfType as $resource) { ?>

                        <?php if ($this->selectedResource == $resource['uri']) { ?>

                            <option value="<?php echo $resource ['uri']; ?>" selected><?php echo $resource ['label']; ?></option>

                        <?php } else { ?>

                            <option value="<?php echo $resource ['uri']; ?>"><?php echo $resource ['label']; ?></option>

                        <?php } ?>

                    <?php } ?>

                    </select>
                </div>
            </div>

            <div class="content">
                <div class="predicateTitle">&nbsp;</div>
                <div class="predicateValue"><input type="submit" value="<?php echo $this->_translate->_('Select'); ?>"></div>
            </div>
        </form>

    <?php } ?>

    <?php if (false !== $this->showForm) { ?>

    <hr>
    <?php $this->forms = array(); ?>
    <?php $this->sectionClass = 'content'; ?>
    
    <?php array_push($this->forms, array($this->form)); ?>
    
    <?php echo $this->render('formgenerator/formsections.phtml') ?>

    <div id="pleaseWaitBox" class="hidden">Please wait...</div>

    <?php } ?>

</form>
<?php if ("box" == $this->layout) { ?>
        </div>
    </div>
<?php } ?>
