<form id="switchFormForm" method="get" action="">   
    <?php echo $this->_translate->_('Alternative forms:'); ?>
    
    <div class="alternativeFormButtons">
        <?php foreach ($this->alternativeForms as $alternativeForm) { ?>
            <a class="button<?php echo $this->currentForm == $alternativeForm['fileName'] ? ' currentactive' : '' ?>" href="http://www.dispedia.local/formgenerator/form/?file=<?php echo $alternativeForm['fileName'] ?>">
                <img src="<?php echo $this->themeUrlBase ?>images/icon-editadd.png">
                <span> <?php echo $alternativeForm['label'] ?></span>
            </a><br>
        <?php } ?>
    </div>
</form>
