<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 


?>

<div class="content">
    <!-- question -->
    <h3><?php echo 'FRAGE'; ?></h3>
    
    <input type="radio" name="<?php echo $element ['name']; ?>"/>
    
    <?php /*echo $topic ['suggestedQuestion']; ?></h3>
    
    <!-- list of options -->
    <?php foreach ( $topic['options'] as $option ) { ?>
    
        <br/>
        <input type="radio" value="" name=""/>
        &nbsp; <?php echo $option ['label']; ?>
    
    <?php }*/ ?>
    
</div>


<div class="content">
