<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 

$element ['outputOptions'] = array ();

// get information about the topic
$topic = $this->alsfrsModel->sparqlQuery(
    'SELECT ?label ?suggestedQuestion
     WHERE {
         <'. $element ['predicateuri'] .'> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://als.dispedia.de/frs/o/Topic> .
         <'. $element ['predicateuri'] .'> <http://www.w3.org/2000/01/rdf-schema#label> ?label .
         <'. $element ['predicateuri'] .'> <http://als.dispedia.de/frs/o/suggestedQuestion> ?suggestedQuestion .
         FILTER (langmatches(lang(?label), "'. $this->selectedLanguage .'"))
     };'
);

$element ['label'] = $topic [0]['label'];
$element ['suggestedQuestion'] = $topic [0]['suggestedQuestion'];

// get information about all options of the topic
foreach ( $element ['typeparameter']['options'] as $option ) {
    
    $o = $this->alsfrsModel->sparqlQuery(
        'SELECT ?optionUri ?label ?score
         WHERE {
             ?optionUri <http://www.w3.org/2000/01/rdf-schema#label> ?label .
             <'. $option .'> <http://www.w3.org/2000/01/rdf-schema#label> ?label .
             <'. $option .'> <http://als.dispedia.de/frs/o/hasScore> ?score .
             FILTER (langmatches(lang(?label), "'. $this->selectedLanguage .'"))
         } 
         ORDER BY ?score;'
    );
    
    $o [0] ['optionValue'] = $option;    
    $element ['outputOptions'][] = $o [0];
}

$entrySelected = false;

// Get latest score
$setOptions = array ();


// get latest timestamp
$latestHealthState = $this->selectedModel->sparqlQuery(
    'PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
     SELECT ?healthState
     WHERE {
         <'. $this->selectedResource .'> <'. $this->formulaParameter ['predicateToHealthState'] .'> ?healthState .
         ?healthState <http://www.dispedia.de/o/hasDate> ?dateTime .
     }
     ORDER BY DESC(xsd:dateTime(?dateTime))
     LIMIT 1;'
); 

if ( true == isset ( $latestHealthState [0] ['healthState'] ) ) { 
    $latestHealthState = '<'. $latestHealthState [0]['healthState'] .'>';
} else {
    $latestHealthState = '?healthState';
}


// if question pertains to a PropertySet
if ('PropertySet' == $element ['typeparameter']['pertainsTo']) {
    
    $tmp = $this->selectedModel->sparqlQuery(
        'SELECT ?setOption
         WHERE {
             <'. $this->selectedResource .'> <'. $this->formulaParameter ['predicateToHealthState'] .'> '. $latestHealthState .' .
             '. $latestHealthState .' <'. $this->formulaParameter ['predicateToPropertySet'] .'> ?propertySet .
             ?propertySet <'. $this->formulaParameter ['predicateToPropertyOption'] .'> ?setOption .
         };'
    );
    
    foreach ( $tmp as $option ) {
        $setOptions [] = $option ['setOption'];
        $entrySelected = true;
    }
    
    
// if question pertains to a SymptomSet
} elseif ('SymptomSet' == $element ['typeparameter']['pertainsTo']) {
 
    $tmp = $this->selectedModel->sparqlQuery(
        'SELECT ?setOption
         WHERE {
             <'. $this->selectedResource .'> <'. $this->formulaParameter ['predicateToHealthState'] .'> '. $latestHealthState .' .
             '. $latestHealthState .' <'. $this->formulaParameter ['predicateToSymptomSet'] .'> ?symptomSet .
             ?symptomSet <'. $this->formulaParameter ['predicateToSymptomOption'] .'> ?setOption .
         };'
    );
    
    foreach ( $tmp as $option ) {
        $setOptions [] = $option ['setOption'];
        $entrySelected = true;
    }
}

?>
<!-- suggested question -->
<div class="alsfrsquestion"><?php echo $element ['suggestedQuestion']; ?></div>

<div class="alsfrsradiobuttons">
<!-- list of options -->
    <?php foreach ( $element ['outputOptions'] as $option ) { ?>
        <div>
            <?php if ( true == in_array ( $option ['optionValue'], $setOptions ) ) { ?>
            
            <input type="radio" name="<?php echo $element ['name'] ?>" value="<?php echo $option ['optionValue']; ?>" checked="checked"/>
            
            <?php } elseif ( false == $entrySelected ) { $entrySelected = true; ?>
            
            <input type="radio" name="<?php echo $element ['name'] ?>" value="<?php echo $option ['optionValue']; ?>" checked="checked"/>
            
            <?php } else { ?>
            
            <input type="radio" name="<?php echo $element ['name'] ?>" value="<?php echo $option ['optionValue']; ?>"/>
            
            <?php } ?>
            
            &nbsp; <?php echo $option ['label']; ?>
        </div>
    <?php } ?>
</div>
