<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 
?>
<?php 

$simpleTopicList = $this->alsfrs->getSimpleTopicList ('de');
$topicsWithOptions = $this->alsfrs->getTopicsWithOptions ( $simpleTopicList );

?>
</div>

<?php foreach ( $topicsWithOptions as $topic ) { ?> 

    <div class="content">
        <!-- question -->
        <h3><?php echo $topic ['suggestedQuestion']; ?></h3>
        
        <!-- list of options -->
        <?php foreach ( $topic['options'] as $option ) { ?>
        
            <br/>
            <input type="radio" value="" name=""/>
            &nbsp; <?php echo $option ['label']; ?>
        
        <?php } ?>
        
    </div>

    <div class="content">
        <div class="predicateTitle">&nbsp;</div>
        <div class="predicateValue">&nbsp;</div>
    </div> 

<?php } ?>
