<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 
?>
<?php 
    $classes = array ();
    foreach ($element ['typeparameter'] as $item)
    {
        $classesResult = array();
        if (isset($item['relation']))
            $classesResult = $this->store->sparqlQuery(
                'SELECT ?uri ?label 
                 WHERE {
                     ?uri <'. $item['relation'] .'> <'. $item['class'] .'>.
                     ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label.
                     FILTER (langmatches(lang(?label), "'. $this->selectedLanguage .'"))
                 };'
            );
        else
        {
            $classesResult = $this->store->sparqlQuery(
                'SELECT ?label 
                 WHERE {
                     <'. $item['class'] .'> <http://www.w3.org/2000/01/rdf-schema#label> ?label.
                     FILTER (langmatches(lang(?label), "'. $this->selectedLanguage .'"))
                 };'
            );
            $classesResult[0]['uri'] = $item['class'];
        }
        $classes = array_merge($classes, $classesResult);
    }
?>
<div class="predicateValue">
    <?php foreach ( $classes as $class ) { ?>
        <input type="checkbox" class="predicateValue_Class" name="<?php echo $element ['name']; ?>" value="<?php echo $class ['uri']; ?>"<?php echo (is_array($element['value']) && false !== array_search($class['uri'], $element['value']) ? ' checked="checked"' : ''); ?>/> <?php echo $class ['label']; ?><br />
    <?php } ?>
</div>
