<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 
?>
<?php 
    $classes = array ();
    
    $classes = $this->selectedModel->sparqlQuery(
        'SELECT ?uri ?label 
         WHERE {
             ?uri <'. $element ['typeparameter']['relation'] .'> <'. $element ['typeparameter']['class'] .'>.
             ?uri <http://www.w3.org/2000/01/rdf-schema#label> ?label.
             FILTER (langmatches(lang(?label), "'. $this->selectedLanguage .'"))
         };'
    );

?>
<div class="predicateValue">
    
    <!-- if person are edit, the "type person" triple must set because the old one will deleted after upadte -->
    <?php if ('edit' == $this->form->getMode()) { ?>
        <input type="checkbox" class="hidden"  name="<?php echo $element ['name']; ?>" value="http://www.dispedia.de/o/Person" checked="checked"/>
    <?php } ?> 
    <?php foreach ( $classes as $class ) { ?>
        <input type="checkbox" class="predicateValue_Resource" name="<?php echo $element ['name']; ?>" value="<?php echo $class ['uri']; ?>"<?php echo (is_array($element['value']) && false != array_search($class['uri'], $element['value']) ? ' checked="checked"' : ''); ?>/> <?php echo $class ['label']; ?><br />
    <?php } ?> 
    
</div>
