<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 
?>

<div class="predicateValue hidden">
    <input type="hidden" class="" id="<?php echo $element['name']; ?>" name="<?php echo $element['name']; ?>" value="<?php echo $element['typeparameter'][0]['value']; ?>"/>
</div>
