<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<div class="predicateValue">
    <select id="<?php echo $element ['name']; ?>" name="<?php echo $element ['name']; ?>" class="predicateValue_List">

        <option value="">- please select -</option>
                    
    <?php foreach ( $element ['typeparameter'] as $par ) { $resourceValue = ''; ?>

        <option value="<?php echo $par ['value']; ?>" <?php echo ($par ['value'] == $resourceValue ? 'selected="selected"' : ''); ?>>
            <?php echo $par ['label']; ?>
        </option>

    <?php } ?>

    </select>
</div>
