<?php
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<?php

    //TODO: remove this output
    //echo "<pre>";
    //var_dump($element);
    //echo "</pre>";
?>

<!-- template for instance from boxed form -->
<div id="<?php echo $element ['typeparameter'][0]['classname']; ?>-template" style="display:none">
    <div class="divMultiplePredicateValue" id="{md5}">
        <input type="checkbox" class="predicateValue_Instance hidden" name="<?php echo $element ['name']; ?>" value="{resourceUri|htmltag}" {checked|htmltag}={checked|htmltag}>
        <div class="divMultipleLabel"><span>{label}</span></div>
        <div class="divMultipleButtons">
            <a href="javascript:elementUp('{md5}')">
                <img src="<?php echo $this->url; ?>../themes/dispedia/images/icons/arrow-up.png">
            </a>
            <a href="javascript:elementDown('{md5}')">
                <img src="<?php echo $this->url; ?>../themes/dispedia/images/icons/arrow-down.png">
            </a>
        </div>       
        <div class="divMultipleButtons">
            <?php if (isset($element ['typeparameter'][0]['editalbe'])) { ?>
                <a href="javascript:openBoxForm('<?php echo $element ['typeparameter'][0]['classname']; ?>', '{resourceUri}')">
                    <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-edit.png">
                </a>
            <?php } ?>
            <a href="javascript:removeElement('{md5}')">
                <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-cancel.png">
            </a>
        </div>
        <div class="clear"></div>
    </div>
</div>

<div class="predicateValue">
    <div class="divMultiplePredicateValue">
        <?php if (isset($element ['typeparameter'][0]['addotherinstances'])) { ?>
            <select id="otherInstances">
                <option value=""><?php echo $this->_translate->_('newInstance'); ?></option>
                <?php foreach ($element ['typeparameter'][0]['allinstances'] as $instanceUri => $instanceLabel) { ?>
                    <option id="<?php echo md5($instanceUri); ?>" value="<?php echo $instanceUri; ?>"><?php echo $instanceLabel; ?></option>
                <?php } ?>
            </select>
            <a href="javascript:addElement('otherInstances', '<?php echo $element ['typeparameter'][0]['classname']; ?>')">
                <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-add.png">
            </a>
        <?php } else { ?>
            <a href="javascript:openBoxForm('<?php echo $element ['typeparameter'][0]['classname']; ?>', '')">
                <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-add.png">
            </a>
        <?php } ?>
    </div>
    <div<?php echo (isset($element ['typeparameter'][0]['editalbe']) ? " id=\"" . $element ['typeparameter'][0]['classname']  . "\"" : "") ?>>
        <?php foreach ( $element ['typeparameter'][0]['instances'] as $instanceUri => $instanceLabel) { ?>
            <div class="divMultiplePredicateValue" id="<?php echo md5($instanceUri); ?>">
                <input type="checkbox" class="predicateValue_Instance hidden" name="<?php echo $element ['name']; ?>" value="<?php echo $instanceUri; ?>" checked="checked" />
                <div class="divMultipleLabel"><span><?php echo $instanceLabel; ?></span></div>
                <div class="divMultipleButtons">
                    <a href="javascript:elementUp('<?php echo md5($instanceUri); ?>')">
                        <img src="<?php echo $this->url; ?>../themes/dispedia/images/icons/arrow-up.png">
                    </a>
                    <a href="javascript:elementDown('<?php echo md5($instanceUri); ?>')">
                        <img src="<?php echo $this->url; ?>../themes/dispedia/images/icons/arrow-down.png">
                    </a>
                </div>
                <div class="divMultipleButtons">
                    <?php if (isset($element ['typeparameter'][0]['editalbe'])) { ?>
                        <a href="javascript:openBoxForm('<?php echo $element ['typeparameter'][0]['classname']; ?>', '<?php echo $instanceUri; ?>')">
                            <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-edit.png">
                        </a>
                    <?php } ?>
                    <a href="javascript:removeElement('<?php echo md5($instanceUri); ?>')">
                        <img src="<?php echo $this->url; ?>../themes/dispedia/images/icon-cancel.png">
                    </a>
                </div>
                <div class="clear"></div>
            </div>
        <?php } ?>
    </div>
</div>
