<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */ 
?>
<?php 
$resources = array ();

// get a list of all resource which are type of a given class
if (false !== strpos ($element ['typeparameter'], 'Patient') || 
    false !== strpos ($element ['typeparameter'], 'Person') )
{
    $resources = $this->selectedModel->sparqlQuery(
        'SELECT ?uri ?firstname ?lastname 
         WHERE {
             ?uri <'. $this->predicateType .'> <'. $element ['typeparameter'] .'>.
             ?uri <'. $this->form->replaceNamespaces ('architecture:') .'firstName> ?firstname.
             ?uri <'. $this->form->replaceNamespaces ('architecture:') .'lastName> ?lastname.
         };'
    );
}
?>
<div class="predicateValue">
    <select id="<?php echo $element ['name']; ?>" name="<?php echo $element ['name']; ?>" class="predicateValue_Resource">

        <option value="">- please select -</option>
                    
    <?php foreach ( $resources as $resource ) { ?>

    <?php if ($element['value'] == $resource['uri']) { ?>
    
        <option value="<?php echo $resource ['uri']; ?>" selected>
            <?php echo $resource ['firstname'] .' '. $resource ['lastname']; ?></option>
    
    <?php } else { ?>

        <option value="<?php echo $resource ['uri']; ?>">
            <?php echo $resource ['firstname'] .' '. $resource ['lastname']; ?></option>

    <?php } ?>
    
    <?php } ?>

    </select>
</div>
