<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<div class="predicateValue">
    <?php if ('report' != $this->form->getFormulaType()) { ?>
    
        <input type="text" id="<?php echo $element ['name']; ?>" name="<?php echo $element ['name']; ?>" value="<?php echo $element ['value']; ?>" class="text predicateValue_Textfield"/>
    
    <?php } else { ?>
    
        <span id="<?php echo $element ['name']; ?>" class="<?php echo ("http://www.w3.org/2000/01/rdf-schema#label" == $element ['predicateuri'] ? 'bold ' : '') ?>predicateValue_Textfield_span"><?php echo $element ['value']; ?></span>

    <?php } ?>
</div>
