<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<div class="predicateValue">
    
    <?php if ('report' != $this->form->getFormulaType()) { ?>
    
        <textarea id="<?php echo $element ['name']; ?>" name="<?php echo $element ['name']; ?>" class="text predicateValue_Textarea"><?php echo $element ['value']; ?></textarea>
        
    <?php } else { ?>
    
        <span id="<?php echo $element ['name']; ?>" class="predicateValue_Textarea_span"><?php echo $element ['value']; ?></span>

    <?php } ?>
</div>
