<?php 
/**
 * @category   OntoWiki
 * @package    OntoWiki_extensions_formgenerator
 * @author     Lars Eidam <larseidam@googlemail.com>
 * @author     Konrad Abicht <konrad@inspirito.de>
 * @copyright  Copyright (c) 2011
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */
?>
<div class="predicateValue">
    <span id="<?php echo $element ['name']; ?>" class="<?php echo ("http://www.w3.org/2000/01/rdf-schema#label" == $element ['predicateuri'] ? 'bold ' : '') ?>predicateValue_Textfield_span"><?php echo $element ['value']; ?></span>
</div>
